### ISSUE TITLE
Initialization error, mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted

### ISSUE THREAD

**Issue by yevon** [gitpod-io/template-flutter#6]
### Bug description

I'm getting errors while trying to use this template, this might be related to something in my setup but maybe yo know something about this. I'm using it in gitpod self-hosted in k3s cluster over an ubuntu OS.

[ 2/13] RUN curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && curl -fsSL https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list     && install-packages build-essential dart libkrb5-dev gcc make gradle android-tools-adb android-tools-fastboot
#5 0.511 container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted
#5 ERROR: process "/bin/bash -c curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && curl -fsSL https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list     && install-packages build-essential dart libkrb5-dev gcc make gradle android-tools-adb android-tools-fastboot" did not complete successfully: exit code: 1

### Steps to reproduce

Just start an empty workspace with this template.

**Comment by yevon** [comment]
Is it related to this? https://github.com/gitpod-io/gitpod/issues/2459

**Comment by axonasif** [comment]
No longer relevant.
